### ISSUE TITLE
Error when using django-allauth in place of django.contrib.auth.

### ISSUE THREAD

**Issue by changeling** [Williano/django-bona-blog#13]
When used in projects using django-allauth, the User relations in several places fai, and yield the following error:

```
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
blog.Article.author: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
blog.Profile.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

System check identified 2 issues (0 silenced).
```

Here's the recommended approach to referencing the User model from the Django documentation:

[Referencing the User model](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#referencing-the-user-model)

I'd really love to see this app in action. It looks amazing, and exactly what I'm looking for. But [django-allauth](https://github.com/pennersr/django-allauth) isn't something I can let go of. It's an great collection of integrated user-related functionalities, and would be be an amazing addition to any project wanting to use your blog app. (Like mine. :D )

[django-allauth](https://github.com/pennersr/django-allauth)
